name: test-team-reviewers
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create report file
        run: date +%s > report.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          team-reviewers: developers
