name: test-team-reviewers
on: workflow_dispatch

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create report file
        run: date +%s > report.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          branch: test1
          title: test1
          team-reviewers: developers

  test2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create report file
        run: date +%s > report.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          branch: test2
          title: test2
          team-reviewers: secret-team
